### ISSUE TITLE
Using vscode-redux-devtools over an existing chrome debug connection

### ISSUE THREAD

**Issue by ankon** [jkzing/vscode-redux-devtools#1]
I'm trying to debug a polymer/redux application with visual studio, and I'm using the chrome debug extension already. I was wondering whether it is (at least theoretically?) feasible to avoid a separate server, and instead inspect the redux state inside the chrome instance directly via the existing connection?

**Comment by jkzing** [comment]
Sadly we can not.

It's because the Chrome extension has the ability to access your redux store directly via Chrome Extension API while a separated  electron app (vscode) does not.  (that's because your application is **running inside Chrome**). 
So what remotedev-server does is, it grabs your redux store from your app, which is running in **Chrome**, and notify the **Remote Devtool** running in **vscode**. This could be very useful when you are debugging a React-Native app, and it is what it made to do.

There is also a Chrome extension does the same work like the vscode-redux-devtools different from Redux Devtools: [RemoteDev](https://chrome.google.com/webstore/detail/remotedev/faicmgpfiaijcedapokpbdejaodbelph).
And if you want to avoid start a local server, there is [http://remotedev.io/](http://remotedev.io/) for you. You can follow find guide here: [https://github.com/zalmoxisus/remote-redux-devtools](https://github.com/zalmoxisus/remote-redux-devtools).

PS: I'll try to explain that in README. :)
